version: '3.8'

services:
  # Apache and PHP service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8-apache
    container_name: hy-php
    ports:
      - "8080:80"
    volumes:
      - /c/Project/PHP/Hong-Yun-Warehouse/src:/var/www/html
    depends_on:
    - mysql
    environment:
    - MYSQL_HOST=hy-mysql
    - MYSQL_USER=root
    - MYSQL_DATABASE=hy_db
    networks:
      - hy-warehouse

  # MySQL service
  mysql:
    image: mysql:8.0
    networks:
      - hy-warehouse
    container_name: hy-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_general_ci
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hy_db
    volumes:
      - ./mysql-data:/var/lib/mysql

  # phpMyAdmin service
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   networks:
  #     - hy-warehouse
  #   container_name: hy-phpmyadmin
  #   ports:
  #     - "8081:80"
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: 123456
  #   depends_on:
  #     - mysql

networks:
  hy-warehouse: